Abbreviate ". ";
Abbreviate ", ";
Abbreviate "Non ";
Abbreviate "è ";
Abbreviate "_to/";
Abbreviate "nulla";
Abbreviate "Hai ";
Abbreviate "à ";
Abbreviate "ent";
Abbreviate "puoi ";
Abbreviate "non ";
Abbreviate "re ";
Abbreviate "uesto ";
Abbreviate "di ";
Abbreviate "ndo";
Abbreviate "cosa ";
Abbreviate "Sei ";
Abbreviate "che ";
Abbreviate "ess";
Abbreviate "chius";
Abbreviate "lla";
Abbreviate "ti ";
Abbreviate "ser";
Abbreviate "zion";
Abbreviate "con";
Abbreviate "par";
Abbreviate "ssa";
Abbreviate "tai ";
Abbreviate "capisco ";
Abbreviate "LookMode";
Abbreviate "una ";
Abbreviate "chi";
Abbreviate "ter";
Abbreviate "to ";
Abbreviate "opra ";
Abbreviate "ci sei ";
Abbreviate "do ";
Abbreviate "l gioco? ";
Abbreviate "per";
Abbreviate "Prima ";
Abbreviate "Inform";
Abbreviate "_array";
Abbreviate "ù ";
Abbreviate "prima";
Abbreviate "fer";
Abbreviate "dire";
Abbreviate "scri";
Abbreviate "da ";
Abbreviate "tion";
Abbreviate "dosso ";
Abbreviate "cor";
Abbreviate "le ";
Abbreviate " in ";
Abbreviate "error";
Abbreviate "ers";
Abbreviate "est";
Abbreviate "are.";
Abbreviate "cos";
Abbreviate "for";
Abbreviate "ono";
Abbreviate "man";
Abbreviate "creat";
Abbreviate "bject";
Abbreviate "a d";
