Abbreviate ". ";
Abbreviate ", ";
Abbreviate "Non ";
Abbreviate "è ";
Abbreviate "_to/";
Abbreviate "nulla";
Abbreviate "à ";
Abbreviate "puoi ";
Abbreviate "ent";
Abbreviate "non ";
Abbreviate "re ";
Abbreviate "di ";
Abbreviate "uesto ";
Abbreviate "ndo";
Abbreviate "cosa ";
Abbreviate "che ";
Abbreviate "nte";
Abbreviate "ti ";
Abbreviate "lla";
Abbreviate "on ";
Abbreviate "o p";
Abbreviate "tai ";
Abbreviate "zioni";
Abbreviate "rima ";
Abbreviate "ssa";
Abbreviate "LookMode";
Abbreviate "una ";
Abbreviate "gioc";
Abbreviate "opra ";
Abbreviate "tto.";
Abbreviate "Sei";
Abbreviate "Inform";
Abbreviate "_array";
Abbreviate "re.";
Abbreviate "ù ";
Abbreviate "zione";
Abbreviate "name";
Abbreviate "rea";
Abbreviate "ter";
Abbreviate " in ";
Abbreviate "ion";
Abbreviate "par";
Abbreviate "per";
Abbreviate "a d";
Abbreviate "apisco";
Abbreviate "i v";
Abbreviate "for";
Abbreviate "chius";
Abbreviate "able";
Abbreviate "ire";
Abbreviate "i s";
Abbreviate "fer";
Abbreviate "che";
Abbreviate "lle";
Abbreviate "tro";
Abbreviate "man";
Abbreviate "ale";
Abbreviate "ing";
Abbreviate "Sho";
Abbreviate "---";
Abbreviate "pro";
Abbreviate "por";
Abbreviate "pos";
Abbreviate "pre";
