Abbreviate ". ";
Abbreviate ", ";
Abbreviate "Non ";
Abbreviate "è ";
Abbreviate "Hai ";
Abbreviate "_to/";
Abbreviate "nulla";
Abbreviate "puoi ";
Abbreviate "à ";
Abbreviate "ent";
Abbreviate "non ";
Abbreviate "re ";
Abbreviate "Sei ";
Abbreviate "di ";
Abbreviate "uesto ";
Abbreviate "ndo";
Abbreviate "cosa ";
Abbreviate "che ";
Abbreviate "ssa";
Abbreviate "to ";
Abbreviate "ti ";
Abbreviate "a d";
Abbreviate "zion";
Abbreviate "gioco";
Abbreviate "par";
Abbreviate "ai ";
Abbreviate "chiu";
Abbreviate "LookMode";
Abbreviate "ci sei ";
Abbreviate "la con";
Abbreviate "ter";
Abbreviate "tro";
Abbreviate "ser";
Abbreviate "Inform";
Abbreviate "_array";
Abbreviate "gli";
Abbreviate "ù ";
Abbreviate "per";
Abbreviate "le ";
Abbreviate "fer";
Abbreviate "pri";
Abbreviate "scri";
Abbreviate "so ";
Abbreviate "tion";
Abbreviate "capi";
Abbreviate "la ";
Abbreviate "na ";
Abbreviate "on ";
Abbreviate "error";
Abbreviate "are.";
Abbreviate "est";
Abbreviate "cos";
Abbreviate "for";
Abbreviate "do ";
Abbreviate "cont";
Abbreviate "no ";
Abbreviate "creat";
Abbreviate "Prim";
Abbreviate "bject";
Abbreviate "co ";
Abbreviate "i a ";
Abbreviate "port";
Abbreviate "opra ";
Abbreviate "Wait";
